#!/usr/bin/env bash

# Apply the EverFocus EAR100T board delta to a stock NVIDIA L4T r39.2 BSP tree.
#
# The EAR100T is an AGX Thor Devkit derivative: it reports the devkit's board ID,
# compatible string and model, and reuses NVIDIA's devkit board config.
# Only the following differ:
#
#   1. QSPI drive strength  - 1X where the devkit uses 2X (6 pins)
#   2. UPHY lane allocation - ODMDATA config 6 instead of the devkit lane file
#   3. Device tree          - PCIe C3 on, MGBE 0-3 and INA238 off
#
# Steps 4 and 5 are not board differences, they work around bugs in the stock BSP.
#
# Usage: apply.sh <Linux_for_Tegra-dir>

set -euo pipefail

fail() {
    echo "error: $*" >&2
    exit 1
}

ldk_dir="${1:?usage: apply.sh <Linux_for_Tegra-dir>}"
[ -d "${ldk_dir}" ] || fail "no such directory: ${ldk_dir}"
ldk_dir="$(cd "${ldk_dir}" && pwd)"
cd "${ldk_dir}"

board="ear100t"
dtb_stem="tegra264-p4071-0000+p3834-0008"
pinmux_stem="tegra264-mb1-bct-pinmux-p3834-xxxx-p4071-0000"
stock_conf="p3834-0008-p4071-0000-nvme.conf"

stock_dtb="kernel/dtb/${dtb_stem}-nv.dtb"
stock_dtsi="bootloader/${pinmux_stem}.dtsi"
stock_pinmux_dts="bootloader/generic/BCT/${pinmux_stem}.dts"
flash_script="tools/kernel_flash/l4t_initrd_flash_internal.sh"
utils_script="unified_flash/tools/flashtools/bootburn_t264_py/flash_utilities.py"
anchor_marker="# EAR100T: anchor the flashing tool names to their directory"

out_conf="${board}.conf"
out_dtb="kernel/dtb/${dtb_stem}-${board}.dtb"
out_dtsi="bootloader/${pinmux_stem}-${board}.dtsi"
out_pinmux_dts="bootloader/generic/BCT/${pinmux_stem}-${board}.dts"

for f in flash.sh "${stock_conf}" "${stock_dtb}" "${stock_dtsi}" \
    "${stock_pinmux_dts}" "${flash_script}" "${utils_script}"; do
    [ -f "${f}" ] || fail "${ldk_dir} is not an L4T r39.2 BSP tree, missing ${f}"
done
command -v fdtput >/dev/null \
    || fail "fdtput not found, install device-tree-compiler"

# 1. Pinmux BCT. The EAR100T's QSPI traces want 1X drive where the devkit uses
#    2X.
sed '/nvidia,pins = "qspi0_/,/};/ s/TEGRA_PIN_2X_DRIVER/TEGRA_PIN_1X_DRIVER/' \
    "${stock_dtsi}" >"${out_dtsi}"
rewrites=$(($(grep -c TEGRA_PIN_1X_DRIVER "${out_dtsi}") \
    - $(grep -c TEGRA_PIN_1X_DRIVER "${stock_dtsi}")))
[ "${rewrites}" -eq 6 ] \
    || fail "expected 6 qspi0 drv-type rewrites, made ${rewrites}"

# The PINMUX_CONFIG entry point is a .dts wrapping the .dtsi above, so point a
# copy of it at ours.
sed "s|${pinmux_stem}\.dtsi|${pinmux_stem}-${board}.dtsi|" \
    "${stock_pinmux_dts}" >"${out_pinmux_dts}"
grep -q "${pinmux_stem}-${board}.dtsi" "${out_pinmux_dts}" \
    || fail "failed to redirect the pinmux include in ${out_pinmux_dts}"

# 2. Device tree. PCIe C3 carries the EAR100T's second RTL8126. All four MGBE
#    MACs are unpopulated and have no UPHY lanes once ODMDATA reallocates them,
#    and stock sets nvidia,force-restart-lane-bringup on each, so leaving them
#    enabled risks retry loops at boot.
install -m 644 "${stock_dtb}" "${out_dtb}"
fdtput -t s "${out_dtb}" "/bus@0/pcie@a808440000" status "okay"
for mac in a808a10000 a808b10000 a808d10000 a808e10000; do
    fdtput -t s "${out_dtb}" "/bus@0/ethernet@${mac}" status "disabled"
done
# The devkit's INA238 power monitor is unpopulated here, so its probe fails.
fdtput -t s "${out_dtb}" "/bus@0/i2c@c600000/ina238@44" status "disabled"

# 3. Board config. Sources the stock devkit conf, then overrides only what the
#    EAR100T changes.
cat >"${out_conf}" <<EOF
# EverFocus EAR100T. Generated by bsp/ear100t/apply.sh - do not edit by hand.
#
# Derived from NVIDIA's AGX Thor Devkit config, which this board is a variant of.

source "\${LDK_DIR}/${stock_conf}";

PINMUX_CONFIG="${pinmux_stem}-${board}.dts";
DTB_FILE="${dtb_stem}-${board}.dtb";
TBCDTB_FILE="\${DTB_FILE}";

# UPHY0 lanes go to PCIe rather than MGBE.
UPHY_CONFIG="";
ODMDATA="uphy0-config-6,pcie@3_status=okay";
EOF

# 4. Flash script fix. The unified flash path T264 invokes tegrarcm_v2 and
# its siblings by bare name, which the nested sudo's secure_path cannot resolve.
# shellcheck disable=SC2016 # literal shell source, must not expand here
stock_invocation='sudo python3 "${FLASH_EXEC}"'
# shellcheck disable=SC2016
patched_invocation='sudo env PATH="${bsp_images_dir}/tools/flashtools/flash:${PATH}" python3 "${FLASH_EXEC}"'

if grep -qF "${patched_invocation}" "${flash_script}"; then
    patch_state="already patched"
else
    [ "$(grep -cF "${stock_invocation}" "${flash_script}")" -eq 1 ] \
        || fail "expected 1 stock flash invocation in ${flash_script}"
    sed -i "s|${stock_invocation}|${patched_invocation}|" "${flash_script}"
    grep -qF "${patched_invocation}" "${flash_script}" \
        || fail "failed to patch ${flash_script}"
    patch_state="patched"
fi

# 5. Flash tool paths. Those names are only anchored to the tools directory when
# isPDK is set, which miniPDK flashing does not set, so anchor them on import.
if grep -qF "${anchor_marker}" "${utils_script}"; then
    anchor_state="already patched"
else
    cat >>"${utils_script}" <<EOF

${anchor_marker}
_flash_dir = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir, "flash"))
for _name, _value in list(vars(flash_utilities).items()):
    if not _name.startswith("f_"):
        continue
    if isinstance(_value, str):
        setattr(flash_utilities, _name, os.path.join(_flash_dir, _value))
    elif isinstance(_value, list):
        setattr(flash_utilities, _name,
                [os.path.join(_flash_dir, _v) for _v in _value])
EOF
    python3 -c "import ast,sys; ast.parse(open(sys.argv[1]).read())" "${utils_script}" \
        || fail "patching ${utils_script} produced invalid Python"
    anchor_state="patched"
fi

echo "Applied the EAR100T delta to ${ldk_dir}"
printf '  %s\n' "${out_conf}" "${out_dtb}" "${out_dtsi}" "${out_pinmux_dts}"
printf '  %s (%s)\n' "${flash_script}" "${patch_state}"
printf '  %s (%s)\n' "${utils_script}" "${anchor_state}"
echo
echo "Install flashing prerequisites, once per host:"
echo "  just bsp-prereqs"
echo
echo "Flash QSPI boot firmware only (board must be in USB recovery mode):"
echo "  just bsp-flash"
